# Font
font_family Maple Mono Normal NL Italic
font_size 12.0

# Cursor
cursor_text_color background
shell_integration no-cursor
cursor_shape beam
cursor_shape_unfocused underline

# Scrollback
scrollback_lines 10000
scrollbar hovered
scrollbar_handle_color foreground
scrollbar_track_color selection_background

# Mouse
# instantly hide mouse when typing
mouse_hide_wait -1.0

# Performance
repaint_delay 6
input_delay 1
sync_to_monitor yes

# Audio
enable_audio_bell no

# Window
window_padding_width 10
window_padding_height 10
background_opacity 0.30
dynamic_background_opacity yes

# Color
cursor #f5e0dc
cursor_text_color #1e1e2e

foreground #e2eefc
selection_foreground #1e1e2e
background #352a59
selection_background #f5e0dc

url_color #89b4fa

# Terminal Colors

# Black
color0 #45475a
color8 #585b70

# Red
color1 #f38ba8
color9 #f38ba8

# Green
color2  #a6e3a1
color10 #a6e3a1

# Yellow
color3  #f9e2af
color11 #f9e2af

# Blue
color4  #89b4fa
color12 #89b4fa

# Magenta
color5  #f5c2e7
color13 #f5c2e7

# Cyan
color6  #94e2d5
color14 #94e2d5

# White
color7  #a6adc8
color15 #bac2de
