# paths
music_directory     "~/Music"
playlist_directory  "~/.config/mpd/playlists"
db_file             "~/.config/mpd/database"
log_file            "~/.config/mpd/mpd.log"
pid_file            "~/.config/mpd/pid"
state_file          "~/.config/mpd/state"

# networking
bind_to_address     "127.0.0.1"
port                "6600"

# pipewire
audio_output {
    type            "pipewire"
    name            "PipeWire Output"
}

# resampling
resampler {
    plugin          "soxr"
    quality         "very high"
}

auto_update         "yes"
restore_paused      "yes"
